// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBARLysy-Z5d02Ma4soeSYUoVTYwZ5OVVs',
    appId: '1:344369504502:web:3476e635379138b1a3ccd7',
    messagingSenderId: '344369504502',
    projectId: 'db46-dd00a',
    authDomain: 'db46-dd00a.firebaseapp.com',
    storageBucket: 'db46-dd00a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUdjWOrjgyQJ-zOB8nuQUOWGnbLINcRBA',
    appId: '1:344369504502:android:a491d6e17100c554a3ccd7',
    messagingSenderId: '344369504502',
    projectId: 'db46-dd00a',
    storageBucket: 'db46-dd00a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-dOsQrZLXbA5_Isg1MNByzYPLVBsv5s',
    appId: '1:344369504502:ios:5a90d21ef67da1cda3ccd7',
    messagingSenderId: '344369504502',
    projectId: 'db46-dd00a',
    storageBucket: 'db46-dd00a.appspot.com',
    iosBundleId: 'com.example.assignmentHml',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx-dOsQrZLXbA5_Isg1MNByzYPLVBsv5s',
    appId: '1:344369504502:ios:5c574d4bea8da781a3ccd7',
    messagingSenderId: '344369504502',
    projectId: 'db46-dd00a',
    storageBucket: 'db46-dd00a.appspot.com',
    iosBundleId: 'com.example.assignmentHml.RunnerTests',
  );
}
